repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.5.1
    hooks:
      - id: prettier
        exclude: ^Pipfile\.loc

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
          - flake8-comprehensions
          - flake8-simplify

  - repo: local
    hooks:
      - id: Test
        name: Run all tests
        language: python
        entry: python -m unittest -h

      - id: stop-if-syntax-error
        name: stop the build if there are Python syntax errors or undefined names
        language: python
        entry: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        types_or: [python, pyi]
        exclude: test/

      - id: errors-warnings-and-chars
        name: exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        language: python
        entry: flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        types_or: [python, pyi]
        exclude: test/
